### ISSUE TITLE
Bad number of player online

### ISSUE THREAD

**Issue by Paul255** [Paul255/ActionFPS-Bots#5]
If an inter is called before the "current-game-status" update (https://actionfps.com/server-updates/) the # of player might not be good.

**Comment by lucasgautheron** [comment]
How long does it usually take ? It is alright if player list is not 100% accurate if it helps to reduce latency

**Comment by Paul255** [comment]
Around 10-15s to be sure data are valid, It won't reduce latency. If it's already not to have an accurate player list I can close this.

**Comment by lucasgautheron** [comment]
I meant, we'd rather preserve low latency than slightly more accurate player lists imo
